from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Thema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fragen=None, antwort=None, code=None, published=None):  # noqa: E501
        """Thema - a model defined in OpenAPI

        :param fragen: The fragen of this Thema.  # noqa: E501
        :type fragen: str
        :param antwort: The antwort of this Thema.  # noqa: E501
        :type antwort: str
        :param code: The code of this Thema.  # noqa: E501
        :type code: str
        :param published: The published of this Thema.  # noqa: E501
        :type published: bool
        """
        self.openapi_types = {
            'fragen': str,
            'antwort': str,
            'code': str,
            'published': bool
        }

        self.attribute_map = {
            'fragen': 'Fragen',
            'antwort': 'Antwort',
            'code': 'Code',
            'published': 'Published'
        }

        self._fragen = fragen
        self._antwort = antwort
        self._code = code
        self._published = published

    @classmethod
    def from_dict(cls, dikt) -> 'Thema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Thema of this Thema.  # noqa: E501
        :rtype: Thema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fragen(self) -> str:
        """Gets the fragen of this Thema.


        :return: The fragen of this Thema.
        :rtype: str
        """
        return self._fragen

    @fragen.setter
    def fragen(self, fragen: str):
        """Sets the fragen of this Thema.


        :param fragen: The fragen of this Thema.
        :type fragen: str
        """
        if fragen is None:
            raise ValueError("Invalid value for `fragen`, must not be `None`")  # noqa: E501

        self._fragen = fragen

    @property
    def antwort(self) -> str:
        """Gets the antwort of this Thema.


        :return: The antwort of this Thema.
        :rtype: str
        """
        return self._antwort

    @antwort.setter
    def antwort(self, antwort: str):
        """Sets the antwort of this Thema.


        :param antwort: The antwort of this Thema.
        :type antwort: str
        """
        if antwort is None:
            raise ValueError("Invalid value for `antwort`, must not be `None`")  # noqa: E501

        self._antwort = antwort

    @property
    def code(self) -> str:
        """Gets the code of this Thema.


        :return: The code of this Thema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Thema.


        :param code: The code of this Thema.
        :type code: str
        """

        self._code = code

    @property
    def published(self) -> bool:
        """Gets the published of this Thema.

        Gibt an, ob das Thema veröffentlicht ist  # noqa: E501

        :return: The published of this Thema.
        :rtype: bool
        """
        return self._published

    @published.setter
    def published(self, published: bool):
        """Sets the published of this Thema.

        Gibt an, ob das Thema veröffentlicht ist  # noqa: E501

        :param published: The published of this Thema.
        :type published: bool
        """
        if published is None:
            raise ValueError("Invalid value for `published`, must not be `None`")  # noqa: E501

        self._published = published
